### ISSUE TITLE
Support Rails 4

### ISSUE THREAD

**Issue by joshuaclayton** [thoughtbot/jack_up#13]

**Comment by gabebw** [comment]
I'm pretty sure I added Rails 4 support (look at the recent commits). Also, the gemspec depends on Rails ~> 4.0: https://github.com/thoughtbot/jack_up/blob/master/jack_up.gemspec

**Comment by joshuaclayton** [comment]
@gabebw whoa hey, that's awesome! I'll close this and get another one in, if you're up for taking a crack at it: Appraisals + testing multiple Ruby versions.

**Comment by joshuaclayton** [comment]
Oh hey I did that already too: https://github.com/thoughtbot/jack_up/issues/14
