### ISSUE TITLE
Rails 5 compatability? 

### ISSUE THREAD

**Issue by kieraneglin** [thoughtbot/jack_up#18]

**Comment by joshuaclayton** [comment]
Does it not work in the latest Rails 5 beta? If not, can you provide a backtrace, or provide a PR to support it?

**Comment by kieraneglin** [comment]
Sure thing!  It seems to just be an issue with the gemspec, since this was the error upon `bundle install`
```
Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails (< 5.1, >= 5.0.0.beta3)

    jack_up was resolved to 0.2.0, which depends on
      rails (~> 4.0)
```
We cloned updated the gemspec to allow Rails 5.  After that it appears to be working just as intended!

**Comment by joshuaclayton** [comment]
@kieraneglin woo, alright! I'd love a PR, but I think we'll also want to get https://github.com/thoughtbot/jack_up/pull/15 merged too - that way, we can also run this against CI with Ruby 2.2.2 and 2.3.0. Any objections to holding off until Travis is up and running?

**Comment by kieraneglin** [comment]
I'll hold off!  As an aside, there doesn't seem to be documentation re: using JackUp when there's an unknown number of upload buttons on a page.  Is that possible?

**Comment by blakeloverain** [comment]
Can this be fixed? This issue has been open for 6 months and I haven't been able to install the gem directly from the main repo, I ended up wasting an hour figuring out how. All it takes is changing one line of ~> to >= . 

Much appreciated.

**Comment by joshuaclayton** [comment]
Given [JackUp has been deprecated](https://github.com/thoughtbot/jack_up/commit/89c9b1ec12e99c1345f09f233c32865b24696d11), I'm closing this.
