### ISSUE TITLE
Create preview for video upload?

### ISSUE THREAD

**Issue by PFDstudio** [thoughtbot/jack_up#19]
We're using jack_up for uploading images and MP4 videos. I'm getting images to preview while uploading by creating dom elements in the on("upload:imageRenderReader", ... function, using the options.image property of the options parameter.

However, I don't know how to get a preview for an MP4 video so I can display that during uploading. I'm using the on("upload:dataRenderReader", ... function, but I don't know how to get a full path to the source video so I can create a dom element for it. options.file only contains the filename without the path.

Thanks.

**Comment by PFDstudio** [comment]
I discovered the dataRenderReady event (not mentioned in the readme), and was able to create a video preview there.

**Comment by joshuaclayton** [comment]
Given [JackUp has been deprecated](https://github.com/thoughtbot/jack_up/commit/89c9b1ec12e99c1345f09f233c32865b24696d11), I'm closing this.
