### ISSUE TITLE
Can't verify CSRF token authenticity 

### ISSUE THREAD

**Issue by JNajera** [thoughtbot/jack_up#4]
Guys finally got your gem running smoothly , but todays i got this error when tryting to upload a file again with exactly the same code.

Processing by ImagensController#create as */*
WARNING: Can't verify CSRF token authenticity

What could be possible doing wrong?

**Comment by joshuaclayton** [comment]
Given [JackUp has been deprecated](https://github.com/thoughtbot/jack_up/commit/89c9b1ec12e99c1345f09f233c32865b24696d11), I'm closing this.
