### ISSUE TITLE
Dragleave firing before leaving droppable zone

### ISSUE THREAD

**Issue by seeRead** [thoughtbot/jack_up#9]
Anyone else having this issue?  If so, I'd be glad to take a shot making a fix.

https://github.com/thoughtbot/jack_up/blob/98b1ba572c2d9389a4e95f55c4ba8bcadc8cdb70/lib/assets/javascripts/jack_up/drag_and_drop.coffee#L17

**Comment by joshuaclayton** [comment]
Given [JackUp has been deprecated](https://github.com/thoughtbot/jack_up/commit/89c9b1ec12e99c1345f09f233c32865b24696d11), I'm closing this.
